# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f1ee87b9d089719185cfb2312db19b64ff25c094c1de3530c0fa5a58a89c0b5c06859ef5dda858e700d58d1f9eefa5f12e1781a7025a4c7e3ee6e0337fd5a7e

test:
  secret_key_base: 329ace80fbea96764793f0c72b03b3a0e5e551ebd86c00f6067340c2db0182b5637b70578f0daeb9923b030a74f8f19e3554a11fe79a035f8b07f9bc4a8cc5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
